/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TesteAplicação;

import DAO.FuncionarioDAO;
import DAO.ProjetoDAO;
import Objetos.Funcionario;
import Objetos.Projeto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Dirce
 */
public class Tela1 extends javax.swing.JFrame {
    private FuncionarioDAO dao;
    private ProjetoDAO dao_proj;
    private Funcionario funcionario;
    private int cursor;
    private List<Funcionario> lista;
    private List<Projeto> lista_proj;
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Tela1
     */
    public Tela1() {
        initComponents();
        btn_func_salvar.setEnabled(false);
        btn_func_cancelar.setEnabled(false);
        tf_func_matricula.setEnabled(false);
        tf_func_nome.setEnabled(false);
        tf_func_data_nasc.setEnabled(false);
        tf_func_endereco.setEnabled(false);
        tf_func_telefone.setEnabled(false);
        tf_func_email.setEnabled(false);
        tf_proj_codigo.setEnabled(false);
        tf_proj_nome.setEnabled(false);
        ta_proj_desc.setEnabled(false);
        
        dao = new FuncionarioDAO();
		
	lista = (ArrayList<Funcionario>)dao.getListar();
	cursor = 0;
	//carregaFuncionario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btn_func_cadastrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_func_salvar = new javax.swing.JButton();
        btn_func_cancelar = new javax.swing.JButton();
        tf_func_matricula = new javax.swing.JTextField();
        tf_func_nome = new javax.swing.JTextField();
        tf_func_data_nasc = new javax.swing.JTextField();
        tf_func_endereco = new javax.swing.JTextField();
        tf_func_telefone = new javax.swing.JTextField();
        tf_func_email = new javax.swing.JTextField();
        btn_func_listar = new javax.swing.JButton();
        btn_func_pesquisar = new javax.swing.JButton();
        btn_func_alterar = new javax.swing.JButton();
        btn_func_remover = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_proj_salvar = new javax.swing.JButton();
        btn_proj_cancelar = new javax.swing.JButton();
        tf_proj_codigo = new javax.swing.JTextField();
        tf_proj_nome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_proj_desc = new javax.swing.JTextArea();
        btn_proj_cadastro = new javax.swing.JButton();
        btn_proj_listar = new javax.swing.JButton();
        btn_proj_alterar = new javax.swing.JButton();
        btn_proj_excluir = new javax.swing.JButton();
        btn_proj_pesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_func_cadastrar.setText("Cadastrar");
        btn_func_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_func_cadastrarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cadastro de Funcionario"));

        jLabel1.setText("Matricula: ");

        jLabel2.setText("Nome:");

        jLabel3.setText("Data de Nascimento: ");

        jLabel4.setText("Endereço: ");

        jLabel5.setText("Telefone:");

        jLabel6.setText("Email: ");

        btn_func_salvar.setText("Salvar");
        btn_func_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_func_salvarActionPerformed(evt);
            }
        });

        btn_func_cancelar.setText("Cancelar");

        tf_func_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_func_matriculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(129, 129, 129)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_func_telefone)
                    .addComponent(tf_func_endereco)
                    .addComponent(tf_func_nome)
                    .addComponent(tf_func_matricula)
                    .addComponent(tf_func_data_nasc)
                    .addComponent(tf_func_email, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btn_func_salvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                .addComponent(btn_func_cancelar)
                .addGap(110, 110, 110))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_func_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_func_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_func_data_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_func_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_func_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_func_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_func_cancelar)
                    .addComponent(btn_func_salvar))
                .addGap(21, 21, 21))
        );

        btn_func_listar.setText("Listar Base");
        btn_func_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_func_listarActionPerformed(evt);
            }
        });

        btn_func_pesquisar.setText("Pesquisar");
        btn_func_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_func_pesquisarActionPerformed(evt);
            }
        });

        btn_func_alterar.setText("Alterar");
        btn_func_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_func_alterarActionPerformed(evt);
            }
        });

        btn_func_remover.setText("Excluir");
        btn_func_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_func_removerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_func_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btn_func_listar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_func_pesquisar)
                        .addGap(91, 91, 91)
                        .addComponent(btn_func_alterar)
                        .addGap(92, 92, 92)
                        .addComponent(btn_func_remover)))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_func_cadastrar)
                    .addComponent(btn_func_listar)
                    .addComponent(btn_func_pesquisar)
                    .addComponent(btn_func_alterar)
                    .addComponent(btn_func_remover))
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Funcionario", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cadastro de Projetos"));

        jLabel7.setText("Código do projeto:");

        jLabel8.setText("Nome:");

        jLabel9.setText("Descrição:");

        btn_proj_salvar.setText("Salvar");
        btn_proj_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proj_salvarActionPerformed(evt);
            }
        });

        btn_proj_cancelar.setText("Cancelar");

        tf_proj_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_proj_codigoActionPerformed(evt);
            }
        });

        ta_proj_desc.setColumns(20);
        ta_proj_desc.setRows(5);
        jScrollPane1.setViewportView(ta_proj_desc);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_proj_nome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_proj_codigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btn_proj_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_proj_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_proj_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_proj_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(btn_proj_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_proj_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_proj_cadastro.setText("Cadastrar");
        btn_proj_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proj_cadastroActionPerformed(evt);
            }
        });

        btn_proj_listar.setText("Listar Base");
        btn_proj_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proj_listarActionPerformed(evt);
            }
        });

        btn_proj_alterar.setText("Alterar");

        btn_proj_excluir.setText("Excluir");

        btn_proj_pesquisar.setText("Pesquisar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_proj_cadastro)
                        .addGap(69, 69, 69)
                        .addComponent(btn_proj_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_proj_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btn_proj_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btn_proj_excluir)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_proj_cadastro)
                    .addComponent(btn_proj_listar)
                    .addComponent(btn_proj_pesquisar)
                    .addComponent(btn_proj_alterar)
                    .addComponent(btn_proj_excluir))
                .addGap(28, 28, 28)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Projeto", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_func_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_func_matriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_func_matriculaActionPerformed

    private void btn_func_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_func_cadastrarActionPerformed
        // TODO add your handling code here:
        btn_func_salvar.setEnabled(true);
        btn_func_cancelar.setEnabled(true);
        tf_func_matricula.setEnabled(true);
        tf_func_nome.setEnabled(true);
        tf_func_data_nasc.setEnabled(true);
        tf_func_endereco.setEnabled(true);
        tf_func_telefone.setEnabled(true);
        tf_func_email.setEnabled(true);
        
        
    }//GEN-LAST:event_btn_func_cadastrarActionPerformed

    private void btn_func_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_func_salvarActionPerformed
        // TODO add your handling code here:
        dao = new FuncionarioDAO();
       dao.adiciona(new Funcionario ( -1L ,tf_func_nome.getText(),
                                           tf_func_data_nasc.getText(),
                                           tf_func_endereco.getText(),
                                           tf_func_telefone.getText(),
                                           tf_func_email.getText()));
       JOptionPane.showMessageDialog(null, "Inserido com sucesso!");
       lista = (ArrayList<Funcionario>)dao.getListar();
			cursor = lista.size()-1;
    }//GEN-LAST:event_btn_func_salvarActionPerformed

    private void btn_func_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_func_listarActionPerformed
        // TODO add your handling code here:
        String titulos[]={"Matricula","Nome:","Data de nascimento:", "Endereço:","Telefone: ", "E-mail:"};
			new TabelaFunc(this, (ArrayList<Funcionario>)dao.getListar(), titulos);
    }//GEN-LAST:event_btn_func_listarActionPerformed

    private void btn_func_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_func_pesquisarActionPerformed
        // TODO add your handling code here:
        String nomeProcurado = JOptionPane.showInputDialog(null, "Entre com o nome a pesquisar:",
				"Pesquisa", JOptionPane.QUESTION_MESSAGE);
                        String titulos[]={"Matricula","Nome:","Data de nascimento:", "Endereço:","Telefone: ", "E-mail:"};
			new TabelaFunc(this, (ArrayList<Funcionario>)dao.getPesquisar(nomeProcurado), titulos);
		
    }//GEN-LAST:event_btn_func_pesquisarActionPerformed

    private void btn_func_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_func_alterarActionPerformed
        // TODO add your handling code here:
        if(janelaConfirmacao("Atualização")) {
				dao.altera(new Funcionario(
                                           Long.parseLong(tf_func_matricula.getText()),
                                           tf_func_nome.getText(),
                                           tf_func_data_nasc.getText(),
                                           tf_func_endereco.getText(),
                                           tf_func_telefone.getText(),
                                           tf_func_email.getText()));
                                JOptionPane.showMessageDialog(null, "Inserido com sucesso!");
				lista = (ArrayList<Funcionario>)dao.getListar();
				//carregaFuncionario();
			}
    }//GEN-LAST:event_btn_func_alterarActionPerformed

    private void btn_func_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_func_removerActionPerformed
        // TODO add your handling code here:
                        //   String  matricula = JOptionPane.showInputDialog(null, "Digite a matricula do candidatao para exclusão:",
			//	"Ok", JOptionPane.QUESTION_MESSAGE);
        if(janelaConfirmacao("Exclusão")) {
				dao.remove(Integer.parseInt(tf_func_matricula.getText()));
				lista = (ArrayList<Funcionario>)dao.getListar();
				if(cursor > 0) cursor--;
				//carregaFuncionario();
			}
    }//GEN-LAST:event_btn_func_removerActionPerformed

    private void btn_proj_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proj_salvarActionPerformed
        // TODO add your handling code here:
       dao_proj = new ProjetoDAO();
       dao_proj.adiciona(new Projeto ( -1L ,tf_proj_nome.getText(),                                           
                                       ta_proj_desc.getText()));
       JOptionPane.showMessageDialog(null, "Inserido com sucesso!");
       lista_proj = (ArrayList<Projeto>)dao_proj.getListar();
       
			cursor = lista_proj.size()-1;
    }//GEN-LAST:event_btn_proj_salvarActionPerformed

    private void tf_proj_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_proj_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_proj_codigoActionPerformed

    private void btn_proj_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proj_cadastroActionPerformed
        // TODO add your handling code here:
        tf_proj_codigo.setEnabled(true);
        tf_proj_nome.setEnabled(true);
        ta_proj_desc.setEnabled(true);
    }//GEN-LAST:event_btn_proj_cadastroActionPerformed

    private void btn_proj_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proj_listarActionPerformed
        // TODO add your handling code here:
        String titulos[]={"Código Projeto","Nome","Descrição"};
			new TabelaProjeto(this, (ArrayList<Projeto>)dao_proj.getListar(), titulos);
    }//GEN-LAST:event_btn_proj_listarActionPerformed
    private boolean janelaConfirmacao(String evento) {
		Object[] options = {"Confirmar", "Cancelar"};
	    int escolha = JOptionPane.showOptionDialog(null,
	    		"Confirma a " + evento + "?", "Funcionario",
	          JOptionPane.YES_NO_OPTION,
	          JOptionPane.QUESTION_MESSAGE,
	          null, options, options[0]);
	    return escolha == 0;
		
	}
    
    public void irParaMatricula(Long matricula) {
		for(int i=0; i<lista.size(); i++)
			if(lista.get(i).getMatricula()== matricula) {
				cursor = i;
				//carregaFuncionario();
				break;
			}
	}
    public void irParaCodigoProjeto(Long codigo) {
		for(int i=0; i<lista_proj.size(); i++)
			if(lista_proj.get(i).getCd_projeto()== codigo) {
				cursor = i;
				//carregaFuncionario();
				break;
			}
	}
    /*private void carregaFuncionario() {
		if(cursor >= lista.size()) limparTela();
		else {
			tf_func_nome.setText(lista.get(cursor).getNome());
			tf_func_data_nasc.setText(lista.get(cursor).getData_nasc());
			tf_func_endereco.setText(lista.get(cursor).getEndereco());
                        tf_func_telefone.setText(lista.get(cursor).getTelefone());
			tf_func_email.setText(lista.get(cursor).getEmail());
			tf_func_matricula.setText("" + lista.get(cursor).getMatricula());
    
		}
	}*/
    private void limparTela() {
		tf_func_nome.setText("");
		tf_func_data_nasc.setText("");
		tf_func_endereco.setText("");
                tf_func_telefone.setText("");
		tf_func_email.setText("");
		tf_func_matricula.setText("");
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_func_alterar;
    private javax.swing.JButton btn_func_cadastrar;
    private javax.swing.JButton btn_func_cancelar;
    private javax.swing.JButton btn_func_listar;
    private javax.swing.JButton btn_func_pesquisar;
    private javax.swing.JButton btn_func_remover;
    private javax.swing.JButton btn_func_salvar;
    private javax.swing.JButton btn_proj_alterar;
    private javax.swing.JButton btn_proj_cadastro;
    private javax.swing.JButton btn_proj_cancelar;
    private javax.swing.JButton btn_proj_excluir;
    private javax.swing.JButton btn_proj_listar;
    private javax.swing.JButton btn_proj_pesquisar;
    private javax.swing.JButton btn_proj_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea ta_proj_desc;
    private javax.swing.JTextField tf_func_data_nasc;
    private javax.swing.JTextField tf_func_email;
    private javax.swing.JTextField tf_func_endereco;
    private javax.swing.JTextField tf_func_matricula;
    private javax.swing.JTextField tf_func_nome;
    private javax.swing.JTextField tf_func_telefone;
    private javax.swing.JTextField tf_proj_codigo;
    private javax.swing.JTextField tf_proj_nome;
    // End of variables declaration//GEN-END:variables
}
